### ISSUE TITLE
Move txn parsing into verify from QUIC

### ISSUE THREAD

**Issue by mmcgee-jump** [firedancer-io/firedancer#1393]
Verify might not want to trust offsets and things populated by QUIC tile.

**Comment by ripatel-fd** [comment]
> Move txn parsing into verify from QUIC

This just kicks the architectural security concern from verify to pack. Pack might not want to do arbitrary memory accesses based on the verify tiles' output. 

In order to verify a transaction signature, only very light parsing is needed (far less than a full fd_txn_t). 
Namely: 1. find the number of signatures and the signature table (look at the first two bytes) 2. find the offset of the public key table

The parsing should probably happen in pack instead. In order to improve performance, the end-to-end communication flow from TPU tile to pack should include some hardened mechanism to attach transaction metadata. (such as the fee payer)

**Comment by felix-asym** [comment]
@ripatel-fd I might be missing something, but wouldn't we have bigger problems if verify is compromised (e.g signature bypass). Why would an attacker try to go from verify to pack?

**Comment by mmcgee-jump** [comment]
It's correct in a sense that the least privilege approach for verify is to just verify the signatures and not do a full parse of the transaction. I guess pack shouldn't trust verify, because it's closer to quic, so easier to compromise?

**Comment by felix-asym** [comment]
I don't have objections to either approach as long as we move the parsing out of QUIC.

Exposing the signature verification to completely unvalidated transactions might make exploitation of a bug in the crypto code easier. But that's mostly a theoretical risk. 

On the other hand, moving parsing to pack reduces complexity of verify so that's a small win.

**Comment by 0x0ece** [comment]
Imo the security argument for moving to pack is weak. And discarding invalid transactions early is prob better. I'm not against parsing txs in pack vs verify, but I wouldn't call out any security benefit.

Quic can write whatever to Verify. So, as soon as Verify receives bytes it should copy them, check signature, and continue. Verify should not trust any of the bytes coming from Quic, especially any parsing (the whole point of this change).

If Verify is under the attacker's control, what's the point of even parsing a txn? Verify can inject whatever it wants, since the following tile (Pack) won't check the signature / integrity. So, from a security pov I think that the only argument we can make is "Verify must be trusted". Then, I'd personally do all lightweight checks to discard invalid txs before doing the expensive sigverify (pre-dedup, parsing), but as I said it's just my personal pref, no strong opinion.

**Comment by ripatel-fd** [comment]
Sounds good to me either way. It's not worth arguing about. 
I agree that the security benefit of isolating verify from downstream is marginal.

The main security benefit is that it stops exploit chains starting at the verify tile.
If downstream tiles are susceptible to memory corruption coming from verify it would theoretically be possible to produce and accept invalid blocks. (e.g. a quic => verify => runtime => voting exploit chain). If Firedancer then was network and RPC supermajority, such a bug would be total loss of funds.

The security of fd_txn_parse and the tile architecture in general is robust enough that we can pretty much assume such an exploit chain is impossible. We have worse attack surface to worry about.

But I just thought that if it's simpler, more performant, and theoretically more secure, why not do it?
Again, don't care either way.
