### ISSUE TITLE
config: switch `max_concurrent_connections` to 2048, check other defaults are sane for production

### ISSUE THREAD

**Issue by mmcgee-jump** [firedancer-io/firedancer#2542]

**Comment by nbridge-jump** [comment]
stream_pool_cnt=4096 is low too

**Comment by ripatel-fd** [comment]
We should consider under provisioning the stream pool / advertising much higher stream limits than we have memory buffers.

The reason is that the vast majority of transactions fits within a single packet.
In the rare case of fragmented transactions, we expect these packets to come in in relatively quick succession (tens of microseconds). Consequently, the stream pool load should never exceed a few thousand entries.

This behavior can result in permanently failed streams (due to acknowledgement of lost data) but that's fine, since we can gracefully recover using the STOP_SENDING frame.

In the case of attackers squatting stream pool slots, new incoming streams should simply evict the oldest streams.
Another worthwhile optimization is to entirely remove stream data buffering from the QUIC layer and drop packets containing out-of-order stream data. 

The ideal behavior would be as follows:
- Each stream pool entry should only be in the order of hundreds of bytes; Just enough to keep metadata for protocol compliance and ACKs
- Payloads of STREAM frames should be directly send to tpu_reasm without another layer of buffering

**Comment by mmcgee-jump** [comment]
Sounds good to me
