### ISSUE TITLE
Add README.md to ballet/disco/funk/tango

### ISSUE THREAD

**Issue by abebeos** [firedancer-io/firedancer#320]
(writing unfiltered, thus you understand the grade of frustration)

Frustration comes up when 

* Directory names don't give a clue about the subsystem/component
* missing READMEs (again no clue)

Please add READMEs to the folders, describing immediately(!) what this is about.

### App/Frank

`app/frank` => I have no idea what this is

then the readme starts with title

`Frankendancer/Frank` => still no clue, am annoyed at this point

https://github.com/firedancer-io/firedancer/blob/main/src/app/frank/README.md

### Expected

Clarity, directness, like in semiconductor documentation, so no mental energy is wasted during the work-in.

(I can go to a club later for dances)

**Comment by gnewsome-jump** [comment]
README.me's already exist in directories that require them currently, otherwise (beyond) sufficient documentation can be found in the headers.

In your above examples, `app/frank` already contains a README.md explaining the application structure

**Comment by ripatel-fd** [comment]
@abebeos Issues reported and contributions sent to the codebase are addressed best-effort. As a small team of contributors, we do not, and cannot guarantee support for individual README files at this time. Consider this software not ready for production deployment nor for external contributions. This will change later in the course of the project's development.

We are have noted your disagreements with documentation practice. I have repeatedly mentioned that efforts to fix those are planned, but currently low priority.

We kindly ask you to respect the [GitHub Community Code of Conduct](https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct) and not to post duplicates or to [post off-topic comments on unrelated issues](https://github.com/firedancer-io/firedancer/pull/302#issuecomment-1534817460).

Otherwise, I am going to follow suit with other organizations who have banned you from commenting for similar behavior. Note that such a ban would not prevent you from accessing the codebase. Firedancer stays freely accessible as an open-source project. Please feel free to fork/create a copy and edit the code as you wish.

**Comment by lheeger-jump** [comment]
I agree with @ripatel-jump. It would be extremely disappointing to have someone who seems to care about this project have to be set to read-only or constructively banned. Not only are your issues already present in mind with our internal team, this makes us doubly aware that it is frustrating to community members when documentation is not available.

That being said, almost everything is under active development and there are numerous comments within the code. Documentation is a major component of delivering this client to the community, so rest assured we would love to have those things.

Here are some things we can improve nonetheless cause it does seem like there is some friction:
- We need more clarity on our code of conduct, contributor policy, and the status of the codebase (not for use in production, as @ripatel-jump mentioned).
- We probably need issue templates and PR templates.
- We could be clearer about timelines or general order of operations of the client development (this is actually very well documented).

As an aside: @abebeos, I would be happy to get on the phone, our Firedancer Discord, or meet in person when we are in the same city to discuss how we can do better at these things.
