### ISSUE TITLE
tiles: incomplete error checking on fseq

### ISSUE THREAD

**Issue by mmcgee-jump** [firedancer-io/firedancer#429]
Following kind of code in `fd_frank_verify.c:90` doesn't check for errors in `join`, `new,` `rx_add` etc

``` 
fd_fctl_t * vin_fctl = fd_fctl_cfg_done( fd_fctl_cfg_rx_add( fd_fctl_join( fd_fctl_new( fd_alloca( FD_FCTL_ALIGN,
                                                                                                 fd_fctl_footprint( 1UL ) ),
                                                                                      1UL ) ),
                                                           vin_mcache_depth, vin_fseq, &vin_fseq_diag[ FD_FSEQ_DIAG_SLOW_CNT ] ),
                                       1UL /*cr_burst*/, vin_cr_max, vin_cr_resume, vin_cr_refill );```

**Comment by ripatel-fd** [comment]
@mmcgee-jump I don't think we need error handling here. The `fd_alloca` is guaranteed to return a memory region with matching alignment and footprint. And fd_fctl_new only returns NULL if that memory region is not matching. The code would just segfault (null deref) if this is not the case. So as long as we have a uint test asserting that this passes, it will always pass. That said, we'd have to document these assumptions so we don't accidentally break them in the future.

**Comment by mmcgee-jump** [comment]
It's not true for `fd_fctl_cfg_rx_add`

**Comment by kbowers-jump** [comment]
Overall, the intent of these APIs is such that the composition is full error trapped if the last part of the composition is error trapped (though you might get extra errors in the log from later in the composition due to failures early in the composition).  If the implementation does not reflect that intent, that should be fixed.  And, regardless, no objection to breaking up the composition and testing individual to cleanup any superfluous log chatter.
